# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'navigator.ui'
#
# Created: Sat Jan 28 09:19:15 2012
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(365, 574)
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(12, 166, 271, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButtonBack = QtGui.QPushButton(Form)
        self.pushButtonBack.setGeometry(QtCore.QRect(290, 160, 61, 51))
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.pushButtonRight = QtGui.QPushButton(Form)
        self.pushButtonRight.setGeometry(QtCore.QRect(220, 60, 70, 51))
        self.pushButtonRight.setObjectName("pushButtonRight")
        self.pushButtonDown = QtGui.QPushButton(Form)
        self.pushButtonDown.setGeometry(QtCore.QRect(140, 106, 70, 51))
        self.pushButtonDown.setObjectName("pushButtonDown")
        self.pushButtonUp = QtGui.QPushButton(Form)
        self.pushButtonUp.setGeometry(QtCore.QRect(140, 10, 70, 51))
        self.pushButtonUp.setObjectName("pushButtonUp")
        self.pushButtonLeft = QtGui.QPushButton(Form)
        self.pushButtonLeft.setGeometry(QtCore.QRect(60, 60, 70, 51))
        self.pushButtonLeft.setObjectName("pushButtonLeft")
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 230, 331, 318))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtGui.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton1 = QtGui.QPushButton(self.widget)
        self.pushButton1.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton1.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton1.setMouseTracking(True)
        self.pushButton1.setObjectName("pushButton1")
        self.gridLayout_3.addWidget(self.pushButton1, 0, 0, 1, 1)
        self.pushButton2 = QtGui.QPushButton(self.widget)
        self.pushButton2.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton2.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton2.setMouseTracking(True)
        self.pushButton2.setObjectName("pushButton2")
        self.gridLayout_3.addWidget(self.pushButton2, 0, 1, 1, 1)
        self.pushButton3 = QtGui.QPushButton(self.widget)
        self.pushButton3.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton3.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton3.setMouseTracking(True)
        self.pushButton3.setObjectName("pushButton3")
        self.gridLayout_3.addWidget(self.pushButton3, 0, 2, 1, 1)
        self.pushButton4 = QtGui.QPushButton(self.widget)
        self.pushButton4.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton4.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton4.setMouseTracking(True)
        self.pushButton4.setObjectName("pushButton4")
        self.gridLayout_3.addWidget(self.pushButton4, 0, 3, 1, 1)
        self.pushButton7 = QtGui.QPushButton(self.widget)
        self.pushButton7.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton7.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton7.setMouseTracking(True)
        self.pushButton7.setObjectName("pushButton7")
        self.gridLayout_3.addWidget(self.pushButton7, 1, 0, 1, 1)
        self.pushButton8 = QtGui.QPushButton(self.widget)
        self.pushButton8.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton8.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton8.setMouseTracking(True)
        self.pushButton8.setObjectName("pushButton8")
        self.gridLayout_3.addWidget(self.pushButton8, 1, 1, 1, 1)
        self.pushButton9 = QtGui.QPushButton(self.widget)
        self.pushButton9.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton9.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton9.setMouseTracking(True)
        self.pushButton9.setObjectName("pushButton9")
        self.gridLayout_3.addWidget(self.pushButton9, 1, 2, 1, 1)
        self.pushButtonA = QtGui.QPushButton(self.widget)
        self.pushButtonA.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonA.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonA.setMouseTracking(True)
        self.pushButtonA.setObjectName("pushButtonA")
        self.gridLayout_3.addWidget(self.pushButtonA, 1, 4, 1, 1)
        self.pushButtonB = QtGui.QPushButton(self.widget)
        self.pushButtonB.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonB.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonB.setMouseTracking(True)
        self.pushButtonB.setObjectName("pushButtonB")
        self.gridLayout_3.addWidget(self.pushButtonB, 1, 5, 1, 1)
        self.pushButtonC = QtGui.QPushButton(self.widget)
        self.pushButtonC.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonC.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonC.setMouseTracking(True)
        self.pushButtonC.setObjectName("pushButtonC")
        self.gridLayout_3.addWidget(self.pushButtonC, 2, 0, 1, 1)
        self.pushButtonD = QtGui.QPushButton(self.widget)
        self.pushButtonD.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonD.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonD.setMouseTracking(True)
        self.pushButtonD.setObjectName("pushButtonD")
        self.gridLayout_3.addWidget(self.pushButtonD, 2, 1, 1, 1)
        self.pushButtonE = QtGui.QPushButton(self.widget)
        self.pushButtonE.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonE.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonE.setMouseTracking(True)
        self.pushButtonE.setObjectName("pushButtonE")
        self.gridLayout_3.addWidget(self.pushButtonE, 2, 2, 1, 1)
        self.pushButtonF = QtGui.QPushButton(self.widget)
        self.pushButtonF.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonF.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonF.setMouseTracking(True)
        self.pushButtonF.setObjectName("pushButtonF")
        self.gridLayout_3.addWidget(self.pushButtonF, 2, 3, 1, 1)
        self.pushButtonG = QtGui.QPushButton(self.widget)
        self.pushButtonG.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonG.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonG.setMouseTracking(True)
        self.pushButtonG.setObjectName("pushButtonG")
        self.gridLayout_3.addWidget(self.pushButtonG, 2, 4, 1, 1)
        self.pushButton5 = QtGui.QPushButton(self.widget)
        self.pushButton5.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton5.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton5.setMouseTracking(True)
        self.pushButton5.setObjectName("pushButton5")
        self.gridLayout_3.addWidget(self.pushButton5, 0, 4, 1, 1)
        self.pushButton0 = QtGui.QPushButton(self.widget)
        self.pushButton0.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton0.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton0.setMouseTracking(True)
        self.pushButton0.setObjectName("pushButton0")
        self.gridLayout_3.addWidget(self.pushButton0, 1, 3, 1, 1)
        self.pushButton6 = QtGui.QPushButton(self.widget)
        self.pushButton6.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton6.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton6.setMouseTracking(True)
        self.pushButton6.setObjectName("pushButton6")
        self.gridLayout_3.addWidget(self.pushButton6, 0, 5, 1, 1)
        self.pushButtonH = QtGui.QPushButton(self.widget)
        self.pushButtonH.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonH.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonH.setMouseTracking(True)
        self.pushButtonH.setObjectName("pushButtonH")
        self.gridLayout_3.addWidget(self.pushButtonH, 2, 5, 1, 1)
        self.pushButtonI = QtGui.QPushButton(self.widget)
        self.pushButtonI.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonI.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonI.setMouseTracking(True)
        self.pushButtonI.setObjectName("pushButtonI")
        self.gridLayout_3.addWidget(self.pushButtonI, 3, 0, 1, 1)
        self.pushButtonJ = QtGui.QPushButton(self.widget)
        self.pushButtonJ.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonJ.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonJ.setMouseTracking(True)
        self.pushButtonJ.setObjectName("pushButtonJ")
        self.gridLayout_3.addWidget(self.pushButtonJ, 3, 1, 1, 1)
        self.pushButtonK = QtGui.QPushButton(self.widget)
        self.pushButtonK.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonK.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonK.setMouseTracking(True)
        self.pushButtonK.setObjectName("pushButtonK")
        self.gridLayout_3.addWidget(self.pushButtonK, 3, 2, 1, 1)
        self.pushButtonL = QtGui.QPushButton(self.widget)
        self.pushButtonL.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonL.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonL.setMouseTracking(True)
        self.pushButtonL.setObjectName("pushButtonL")
        self.gridLayout_3.addWidget(self.pushButtonL, 3, 3, 1, 1)
        self.pushButtonM = QtGui.QPushButton(self.widget)
        self.pushButtonM.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonM.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonM.setMouseTracking(True)
        self.pushButtonM.setObjectName("pushButtonM")
        self.gridLayout_3.addWidget(self.pushButtonM, 3, 4, 1, 1)
        self.pushButtonN = QtGui.QPushButton(self.widget)
        self.pushButtonN.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonN.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonN.setMouseTracking(True)
        self.pushButtonN.setObjectName("pushButtonN")
        self.gridLayout_3.addWidget(self.pushButtonN, 3, 5, 1, 1)
        self.pushButtonO = QtGui.QPushButton(self.widget)
        self.pushButtonO.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonO.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonO.setMouseTracking(True)
        self.pushButtonO.setObjectName("pushButtonO")
        self.gridLayout_3.addWidget(self.pushButtonO, 4, 0, 1, 1)
        self.pushButtonP = QtGui.QPushButton(self.widget)
        self.pushButtonP.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonP.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonP.setMouseTracking(True)
        self.pushButtonP.setObjectName("pushButtonP")
        self.gridLayout_3.addWidget(self.pushButtonP, 4, 1, 1, 1)
        self.pushButtonQ = QtGui.QPushButton(self.widget)
        self.pushButtonQ.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonQ.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonQ.setMouseTracking(True)
        self.pushButtonQ.setObjectName("pushButtonQ")
        self.gridLayout_3.addWidget(self.pushButtonQ, 4, 2, 1, 1)
        self.pushButtonR = QtGui.QPushButton(self.widget)
        self.pushButtonR.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonR.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonR.setMouseTracking(True)
        self.pushButtonR.setObjectName("pushButtonR")
        self.gridLayout_3.addWidget(self.pushButtonR, 4, 3, 1, 1)
        self.pushButtonS = QtGui.QPushButton(self.widget)
        self.pushButtonS.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonS.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonS.setMouseTracking(True)
        self.pushButtonS.setObjectName("pushButtonS")
        self.gridLayout_3.addWidget(self.pushButtonS, 4, 4, 1, 1)
        self.pushButtonT = QtGui.QPushButton(self.widget)
        self.pushButtonT.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonT.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonT.setMouseTracking(True)
        self.pushButtonT.setObjectName("pushButtonT")
        self.gridLayout_3.addWidget(self.pushButtonT, 4, 5, 1, 1)
        self.pushButtonU = QtGui.QPushButton(self.widget)
        self.pushButtonU.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonU.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonU.setMouseTracking(True)
        self.pushButtonU.setObjectName("pushButtonU")
        self.gridLayout_3.addWidget(self.pushButtonU, 5, 0, 1, 1)
        self.pushButtonV = QtGui.QPushButton(self.widget)
        self.pushButtonV.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonV.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonV.setMouseTracking(True)
        self.pushButtonV.setObjectName("pushButtonV")
        self.gridLayout_3.addWidget(self.pushButtonV, 5, 1, 1, 1)
        self.pushButtonW = QtGui.QPushButton(self.widget)
        self.pushButtonW.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonW.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonW.setMouseTracking(True)
        self.pushButtonW.setObjectName("pushButtonW")
        self.gridLayout_3.addWidget(self.pushButtonW, 5, 2, 1, 1)
        self.pushButtonX = QtGui.QPushButton(self.widget)
        self.pushButtonX.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonX.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonX.setMouseTracking(True)
        self.pushButtonX.setObjectName("pushButtonX")
        self.gridLayout_3.addWidget(self.pushButtonX, 5, 3, 1, 1)
        self.pushButtonZ = QtGui.QPushButton(self.widget)
        self.pushButtonZ.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonZ.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonZ.setMouseTracking(True)
        self.pushButtonZ.setObjectName("pushButtonZ")
        self.gridLayout_3.addWidget(self.pushButtonZ, 5, 5, 1, 1)
        self.pushButtonY = QtGui.QPushButton(self.widget)
        self.pushButtonY.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonY.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonY.setMouseTracking(True)
        self.pushButtonY.setObjectName("pushButtonY")
        self.gridLayout_3.addWidget(self.pushButtonY, 5, 4, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBack.setText(QtGui.QApplication.translate("Form", "<=", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRight.setText(QtGui.QApplication.translate("Form", "right", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDown.setText(QtGui.QApplication.translate("Form", "down", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonUp.setText(QtGui.QApplication.translate("Form", "up", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLeft.setText(QtGui.QApplication.translate("Form", "left", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton1.setText(QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton2.setText(QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton3.setText(QtGui.QApplication.translate("Form", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton4.setText(QtGui.QApplication.translate("Form", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton7.setText(QtGui.QApplication.translate("Form", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton8.setText(QtGui.QApplication.translate("Form", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton9.setText(QtGui.QApplication.translate("Form", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonA.setText(QtGui.QApplication.translate("Form", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonB.setText(QtGui.QApplication.translate("Form", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonC.setText(QtGui.QApplication.translate("Form", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonD.setText(QtGui.QApplication.translate("Form", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonE.setText(QtGui.QApplication.translate("Form", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonF.setText(QtGui.QApplication.translate("Form", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonG.setText(QtGui.QApplication.translate("Form", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton5.setText(QtGui.QApplication.translate("Form", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton0.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton6.setText(QtGui.QApplication.translate("Form", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonH.setText(QtGui.QApplication.translate("Form", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonI.setText(QtGui.QApplication.translate("Form", "I", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonJ.setText(QtGui.QApplication.translate("Form", "J", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonK.setText(QtGui.QApplication.translate("Form", "K", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonL.setText(QtGui.QApplication.translate("Form", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonM.setText(QtGui.QApplication.translate("Form", "M", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonN.setText(QtGui.QApplication.translate("Form", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonO.setText(QtGui.QApplication.translate("Form", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonP.setText(QtGui.QApplication.translate("Form", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonQ.setText(QtGui.QApplication.translate("Form", "Q", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonR.setText(QtGui.QApplication.translate("Form", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonS.setText(QtGui.QApplication.translate("Form", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonT.setText(QtGui.QApplication.translate("Form", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonU.setText(QtGui.QApplication.translate("Form", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonV.setText(QtGui.QApplication.translate("Form", "V", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonW.setText(QtGui.QApplication.translate("Form", "W", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonX.setText(QtGui.QApplication.translate("Form", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonZ.setText(QtGui.QApplication.translate("Form", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonY.setText(QtGui.QApplication.translate("Form", "Y", None, QtGui.QApplication.UnicodeUTF8))

#from here ...
        QtCore.QObject.connect(self.pushButton0, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButton1, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButton2, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButton3, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButton4, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButton5, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButton6, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButton7, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButton8, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButton9, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonA, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonB, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonC, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonD, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonE, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonF, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonG, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonH, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonI, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonJ, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonK, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonL, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonM, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonN, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonO, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonP, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonQ, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonR, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonS, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonT, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonU, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonV, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonW, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonX, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonY, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        QtCore.QObject.connect(self.pushButtonZ, QtCore.SIGNAL("clicked()"), Form.keyPadSlot)
        
        QtCore.QObject.connect(self.pushButtonBack, QtCore.SIGNAL("clicked()"), Form.backButtonSlot)

        QtCore.QObject.connect(self.pushButtonRight, QtCore.SIGNAL("clicked()"), Form.directionSlot)
	QtCore.QObject.connect(self.pushButtonLeft, QtCore.SIGNAL("clicked()"), Form.directionSlot)	
	QtCore.QObject.connect(self.pushButtonDown, QtCore.SIGNAL("clicked()"), Form.directionSlot)
	QtCore.QObject.connect(self.pushButtonUp, QtCore.SIGNAL("clicked()"), Form.directionSlot)
#upto here....


class navi(QtGui.QWidget):

    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.ui = Ui_Form()
        self.ui.setupUi(self)

    def keyPadSlot(self):
        previoustext =  self.ui.lineEdit.text()
        self.ui.lineEdit.setText( previoustext + self.sender().text() )
        self.emit(QtCore.SIGNAL('textChanged(PyQt_PyObject)'),self.ui.lineEdit.text())

    def backButtonSlot(self):
        previoustext =  self.ui.lineEdit.text()
        self.ui.lineEdit.setText( previoustext[0:-1] )
        self.emit(QtCore.SIGNAL('textChanged(PyQt_PyObject)'),self.ui.lineEdit.text())   
    

    def directionSlot(self):
        self.emit(QtCore.SIGNAL('direction(PyQt_PyObject)'),self.sender().text())
  
    def test(self,name):
       print name



if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = navi()
    QtCore.QObject.connect(Form, QtCore.SIGNAL("textChanged(PyQt_PyObject)"), Form.test)
    Form.show()
    sys.exit(app.exec_())

